export const TREND_RUNNER_PARAMS = {
  commissionRate: 0.0005,
  slippageBps: 5,
  minEntryHoldScore: 70,
  minReentryHoldScore: 90,
  globalBearMinHoldScore: 90,
  emaFastLen: 20,
  emaSlowLen: 50,
  emaTrendLen: 200,
  rsiLen: 14,
  rsiLongMin: 45,
  rsiLongMax: 85,
  atrLen: 14,
  atrStopMultiple: 2.2,
  weeklyEmaLen: 30,
  weeklySlopeLookback: 4,
  slopeLookback: 20,
  pullbackLookback: 12,
  pullbackTolerancePct: 0.7,
  breakoutLen: 25,
  emaPersistenceLen: 200,
  tp1RrMin: 1,
  tp1RrMax: 3,
  tp1QtyMax: 60,
  tp1QtyMin: 10,
  trailAtrMin: 2.5,
  trailAtrMax: 8,
  finalTpMin: 4,
  finalTpMax: 25,
  useFinalTp: false,
  exitOnRegimeLoss: true,
};

export const TREND_RUNNER_PORTFOLIO = {
  positionPct: 2.75,
  minPositionUsd: 20,
  allowMargin: false,
  allowFractionalShares: true,
  pyramidSameAsset: false,
};

const ETF_NAMES = {
  AGG: "iShares Core U.S. Aggregate Bond ETF",
  BND: "Vanguard Total Bond Market ETF",
  DBC: "Invesco DB Commodity Index Tracking Fund",
  DIA: "SPDR Dow Jones Industrial Average ETF Trust",
  EEM: "iShares MSCI Emerging Markets ETF",
  EFA: "iShares MSCI EAFE ETF",
  EMB: "iShares J.P. Morgan USD Emerging Markets Bond ETF",
  EWA: "iShares MSCI Australia ETF",
  EWC: "iShares MSCI Canada ETF",
  EWG: "iShares MSCI Germany ETF",
  EWJ: "iShares MSCI Japan ETF",
  EWT: "iShares MSCI Taiwan ETF",
  EWU: "iShares MSCI United Kingdom ETF",
  EWW: "iShares MSCI Mexico ETF",
  EWY: "iShares MSCI South Korea ETF",
  EWZ: "iShares MSCI Brazil ETF",
  FXI: "iShares China Large-Cap ETF",
  GDX: "VanEck Gold Miners ETF",
  GDXJ: "VanEck Junior Gold Miners ETF",
  HYG: "iShares iBoxx High Yield Corporate Bond ETF",
  IBB: "iShares Biotechnology ETF",
  IEF: "iShares 7-10 Year Treasury Bond ETF",
  ITB: "iShares U.S. Home Construction ETF",
  KRE: "SPDR S&P Regional Banking ETF",
  LQD: "iShares iBoxx Investment Grade Corporate Bond ETF",
  MDY: "SPDR S&P MidCap 400 ETF Trust",
  SHY: "iShares 1-3 Year Treasury Bond ETF",
  SLV: "iShares Silver Trust",
  SMH: "VanEck Semiconductor ETF",
  TIP: "iShares TIPS Bond ETF",
  USO: "United States Oil Fund",
  VEA: "Vanguard FTSE Developed Markets ETF",
  VNQ: "Vanguard Real Estate ETF",
  VTI: "Vanguard Total Stock Market ETF",
  VWO: "Vanguard FTSE Emerging Markets ETF",
  XBI: "SPDR S&P Biotech ETF",
  XHB: "SPDR S&P Homebuilders ETF",
  XLB: "Materials Select Sector SPDR Fund",
  XLF: "Financial Select Sector SPDR Fund",
  XLI: "Industrial Select Sector SPDR Fund",
  XLK: "Technology Select Sector SPDR Fund",
  XLP: "Consumer Staples Select Sector SPDR Fund",
  XLU: "Utilities Select Sector SPDR Fund",
  XLV: "Health Care Select Sector SPDR Fund",
  XLY: "Consumer Discretionary Select Sector SPDR Fund",
  XLE: "Energy Select Sector SPDR Fund",
  XRT: "SPDR S&P Retail ETF",
};

const STOCK_NAMES = {
  AAPL: "Apple Inc.",
  ABT: "Abbott Laboratories",
  ADBE: "Adobe Inc.",
  AMAT: "Applied Materials, Inc.",
  AMD: "Advanced Micro Devices, Inc.",
  AMGN: "Amgen Inc.",
  AMZN: "Amazon.com, Inc.",
  AVGO: "Broadcom Inc.",
  AXP: "American Express Company",
  BA: "Boeing Company",
  BAC: "Bank of America Corporation",
  BRK: "Berkshire Hathaway Inc.",
  "BRK-B": "Berkshire Hathaway Inc. Class B",
  CAT: "Caterpillar Inc.",
  COP: "ConocoPhillips",
  COST: "Costco Wholesale Corporation",
  CRM: "Salesforce, Inc.",
  CSCO: "Cisco Systems, Inc.",
  CVX: "Chevron Corporation",
  DE: "Deere & Company",
  DHR: "Danaher Corporation",
  DIS: "The Walt Disney Company",
  FDX: "FedEx Corporation",
  GLDM: "SPDR Gold MiniShares Trust",
  GLD: "SPDR Gold Shares",
  GOOG: "Alphabet Inc. Class C",
  GOOGL: "Alphabet Inc. Class A",
  GS: "Goldman Sachs Group, Inc.",
  HD: "The Home Depot, Inc.",
  HON: "Honeywell International Inc.",
  IBM: "International Business Machines Corporation",
  INTC: "Intel Corporation",
  ISRG: "Intuitive Surgical, Inc.",
  IWM: "iShares Russell 2000 ETF",
  JNJ: "Johnson & Johnson",
  JPM: "JPMorgan Chase & Co.",
  KLAC: "KLA Corporation",
  KO: "The Coca-Cola Company",
  LLY: "Eli Lilly and Company",
  LMT: "Lockheed Martin Corporation",
  LOW: "Lowe's Companies, Inc.",
  LRCX: "Lam Research Corporation",
  MA: "Mastercard Incorporated",
  MCD: "McDonald's Corporation",
  MDT: "Medtronic plc",
  META: "Meta Platforms, Inc.",
  MRK: "Merck & Co., Inc.",
  MS: "Morgan Stanley",
  MSFT: "Microsoft Corporation",
  NFLX: "Netflix, Inc.",
  NKE: "NIKE, Inc.",
  NVDA: "NVIDIA Corporation",
  ORCL: "Oracle Corporation",
  PEP: "PepsiCo, Inc.",
  PFE: "Pfizer Inc.",
  PG: "Procter & Gamble Company",
  QCOM: "QUALCOMM Incorporated",
  SBUX: "Starbucks Corporation",
  SLB: "Schlumberger Limited",
  SPY: "SPDR S&P 500 ETF Trust",
  SCHD: "Schwab U.S. Dividend Equity ETF",
  TLT: "iShares 20+ Year Treasury Bond ETF",
  TMO: "Thermo Fisher Scientific Inc.",
  TSLA: "Tesla, Inc.",
  TXN: "Texas Instruments Incorporated",
  UNH: "UnitedHealth Group Incorporated",
  UNP: "Union Pacific Corporation",
  UPS: "United Parcel Service, Inc.",
  V: "Visa Inc.",
  VOO: "Vanguard S&P 500 ETF",
  WFC: "Wells Fargo & Company",
  WMT: "Walmart Inc.",
  XOM: "Exxon Mobil Corporation",
};

const ADR_NAMES = {
  ASML: "ASML Holding N.V.",
  AZN: "AstraZeneca PLC",
  BHP: "BHP Group Limited",
  BP: "BP p.l.c.",
  HSBC: "HSBC Holdings plc",
  INFY: "Infosys Limited",
  MELI: "MercadoLibre, Inc.",
  NVO: "Novo Nordisk A/S",
  PBR: "Petroleo Brasileiro S.A. - Petrobras",
  RIO: "Rio Tinto Group",
  RY: "Royal Bank of Canada",
  SAP: "SAP SE",
  SHEL: "Shell plc",
  SONY: "Sony Group Corporation",
  TD: "The Toronto-Dominion Bank",
  TM: "Toyota Motor Corporation",
  TSM: "Taiwan Semiconductor Manufacturing Company Limited",
  TTE: "TotalEnergies SE",
  UL: "Unilever PLC",
  VALE: "Vale S.A.",
};

const CRYPTO_NAMES = {
  ADA: "Cardano",
  AVAX: "Avalanche",
  BCH: "Bitcoin Cash",
  DOGE: "Dogecoin",
  DOT: "Polkadot",
  LINK: "Chainlink",
  LTC: "Litecoin",
  XRP: "XRP",
};

function yahooAsset(symbol, market, name = symbol) {
  return {
    symbol,
    displaySymbol: symbol,
    dataSymbol: symbol,
    name,
    market,
    broker: "etoro",
    dataSource: "yahoo",
    quoteCurrency: "USD",
    minHistoryYears: 15,
  };
}

function cryptoAsset(base, name = base) {
  const symbol = `${base}USDT`;
  return {
    symbol,
    displaySymbol: symbol,
    dataSymbol: symbol,
    name,
    market: "crypto",
    broker: "binance",
    dataSource: "binance",
    quoteCurrency: "USDT",
    minHistoryYears: 7,
  };
}

const baseUniverse = [
  yahooAsset("SPY", "etf", "SPDR S&P 500 ETF Trust"),
  yahooAsset("QQQ", "etf", "Invesco QQQ Trust"),
  yahooAsset("IWM", "etf", "iShares Russell 2000 ETF"),
  yahooAsset("GLD", "etf", "SPDR Gold Shares"),
  yahooAsset("TLT", "etf", "iShares 20+ Year Treasury Bond ETF"),
  yahooAsset("XLE", "etf", "Energy Select Sector SPDR Fund"),
  yahooAsset("XLV", "etf", "Health Care Select Sector SPDR Fund"),
  yahooAsset("VOO", "etf", "Vanguard S&P 500 ETF"),
  yahooAsset("SCHD", "etf", "Schwab U.S. Dividend Equity ETF"),
  yahooAsset("GLDM", "etf", "SPDR Gold MiniShares Trust"),
  yahooAsset("AAPL", "stock", "Apple Inc."),
  yahooAsset("MSFT", "stock", "Microsoft Corporation"),
  yahooAsset("NVDA", "stock", "NVIDIA Corporation"),
  yahooAsset("AMZN", "stock", "Amazon.com, Inc."),
  yahooAsset("JPM", "stock", "JPMorgan Chase & Co."),
  yahooAsset("XOM", "stock", "Exxon Mobil Corporation"),
  yahooAsset("KO", "stock", "The Coca-Cola Company"),
  yahooAsset("WMT", "stock", "Walmart Inc."),
  yahooAsset("BRK-B", "stock", "Berkshire Hathaway Inc. Class B"),
  yahooAsset("META", "stock", "Meta Platforms, Inc."),
  cryptoAsset("BTC", "Bitcoin"),
  cryptoAsset("ETH", "Ethereum"),
  cryptoAsset("BNB", "BNB"),
  cryptoAsset("SOL", "Solana"),
];

const etfs = [
  "DIA", "MDY", "VTI", "VEA", "VWO", "EFA", "EEM", "EWJ", "EWU", "EWG",
  "EWC", "EWA", "EWY", "EWZ", "EWT", "EWW", "FXI", "XLF", "XLK", "XLY",
  "XLP", "XLU", "XLI", "XLB", "SMH", "IBB", "XBI", "XRT", "KRE", "ITB",
  "XHB", "GDX", "GDXJ", "VNQ", "SLV", "USO", "DBC", "IEF", "SHY", "TIP",
  "AGG", "BND", "LQD", "HYG", "EMB",
];

const stocks = [
  "GOOGL", "GOOG", "TSLA", "BAC", "WFC", "GS", "MS", "V", "MA", "AXP",
  "UNH", "JNJ", "PFE", "MRK", "ABT", "TMO", "DHR", "MDT", "ISRG", "AMGN",
  "LLY", "PG", "PEP", "COST", "HD", "LOW", "MCD", "SBUX", "NKE", "DIS",
  "NFLX", "ORCL", "CSCO", "IBM", "INTC", "AMD", "QCOM", "TXN", "AVGO", "CRM",
  "ADBE", "AMAT", "LRCX", "KLAC", "CAT", "DE", "HON", "UNP", "UPS", "FDX",
  "BA", "LMT", "CVX", "COP", "SLB",
];

const adrs = [
  "TSM", "ASML", "SAP", "TM", "SONY", "NVO", "AZN", "UL", "BHP", "RIO",
  "VALE", "PBR", "BP", "SHEL", "TTE", "HSBC", "RY", "TD", "INFY", "MELI",
];

const cryptos = ["ADA", "XRP", "DOGE", "LTC", "BCH", "LINK", "DOT", "AVAX"];

export const TREND_RUNNER_UNIVERSE = [
  ...baseUniverse,
  ...etfs.map((symbol) => yahooAsset(symbol, "etf", ETF_NAMES[symbol] ?? symbol)),
  ...stocks.map((symbol) => yahooAsset(symbol, "stock", STOCK_NAMES[symbol] ?? symbol)),
  ...adrs.map((symbol) => yahooAsset(symbol, "adr", ADR_NAMES[symbol] ?? symbol)),
  ...cryptos.map((symbol) => cryptoAsset(symbol, CRYPTO_NAMES[symbol] ?? symbol)),
];
