export const TREND_RUNNER_PARAMS = {
  commissionRate: 0.0005,
  slippageBps: 5,
  minEntryHoldScore: 70,
  minReentryHoldScore: 90,
  globalBearMinHoldScore: 90,
  emaFastLen: 20,
  emaSlowLen: 50,
  emaTrendLen: 200,
  rsiLen: 14,
  rsiLongMin: 45,
  rsiLongMax: 85,
  atrLen: 14,
  atrStopMultiple: 2.2,
  weeklyEmaLen: 30,
  weeklySlopeLookback: 4,
  slopeLookback: 20,
  pullbackLookback: 12,
  pullbackTolerancePct: 0.7,
  breakoutLen: 25,
  emaPersistenceLen: 200,
  tp1RrMin: 1,
  tp1RrMax: 3,
  tp1QtyMax: 60,
  tp1QtyMin: 10,
  trailAtrMin: 2.5,
  trailAtrMax: 8,
  finalTpMin: 4,
  finalTpMax: 25,
  useFinalTp: false,
  exitOnRegimeLoss: true,
};

export const TREND_RUNNER_PORTFOLIO = {
  positionPct: 2.75,
  minPositionUsd: 20,
  individualStockMinSignalUsd: 1000,
  allowMargin: false,
  allowFractionalShares: true,
  pyramidSameAsset: false,
};

const ETF_NAMES = {
  AGG: "iShares Core U.S. Aggregate Bond ETF",
  BND: "Vanguard Total Bond Market ETF",
  DBC: "Invesco DB Commodity Index Tracking Fund",
  DIA: "SPDR Dow Jones Industrial Average ETF Trust",
  EEM: "iShares MSCI Emerging Markets ETF",
  EFA: "iShares MSCI EAFE ETF",
  EMB: "iShares J.P. Morgan USD Emerging Markets Bond ETF",
  EWA: "iShares MSCI Australia ETF",
  EWC: "iShares MSCI Canada ETF",
  EWG: "iShares MSCI Germany ETF",
  EWJ: "iShares MSCI Japan ETF",
  EWT: "iShares MSCI Taiwan ETF",
  EWU: "iShares MSCI United Kingdom ETF",
  EWW: "iShares MSCI Mexico ETF",
  EWY: "iShares MSCI South Korea ETF",
  EWZ: "iShares MSCI Brazil ETF",
  FXI: "iShares China Large-Cap ETF",
  GDX: "VanEck Gold Miners ETF",
  GDXJ: "VanEck Junior Gold Miners ETF",
  HYG: "iShares iBoxx High Yield Corporate Bond ETF",
  IBB: "iShares Biotechnology ETF",
  IEF: "iShares 7-10 Year Treasury Bond ETF",
  ITB: "iShares U.S. Home Construction ETF",
  KRE: "SPDR S&P Regional Banking ETF",
  LQD: "iShares iBoxx Investment Grade Corporate Bond ETF",
  MDY: "SPDR S&P MidCap 400 ETF Trust",
  SHY: "iShares 1-3 Year Treasury Bond ETF",
  SLV: "iShares Silver Trust",
  SMH: "VanEck Semiconductor ETF",
  TIP: "iShares TIPS Bond ETF",
  USO: "United States Oil Fund",
  VEA: "Vanguard FTSE Developed Markets ETF",
  VNQ: "Vanguard Real Estate ETF",
  VTI: "Vanguard Total Stock Market ETF",
  VWO: "Vanguard FTSE Emerging Markets ETF",
  XBI: "SPDR S&P Biotech ETF",
  XHB: "SPDR S&P Homebuilders ETF",
  XLB: "Materials Select Sector SPDR Fund",
  XLF: "Financial Select Sector SPDR Fund",
  XLI: "Industrial Select Sector SPDR Fund",
  XLK: "Technology Select Sector SPDR Fund",
  XLP: "Consumer Staples Select Sector SPDR Fund",
  XLU: "Utilities Select Sector SPDR Fund",
  XLV: "Health Care Select Sector SPDR Fund",
  XLY: "Consumer Discretionary Select Sector SPDR Fund",
  XLE: "Energy Select Sector SPDR Fund",
  XRT: "SPDR S&P Retail ETF",
  IVV: "iShares Core S&P 500 ETF",
  SPLG: "SPDR Portfolio S&P 500 ETF",
  SCHX: "Schwab U.S. Large-Cap ETF",
  ITOT: "iShares Core S&P Total U.S. Stock Market ETF",
  IWB: "iShares Russell 1000 ETF",
  IWV: "iShares Russell 3000 ETF",
  VV: "Vanguard Large-Cap ETF",
  MGC: "Vanguard Mega Cap ETF",
  OEF: "iShares S&P 100 ETF",
  IWF: "iShares Russell 1000 Growth ETF",
  IWD: "iShares Russell 1000 Value ETF",
  VUG: "Vanguard Growth ETF",
  VTV: "Vanguard Value ETF",
  SCHG: "Schwab U.S. Large-Cap Growth ETF",
  SCHV: "Schwab U.S. Large-Cap Value ETF",
  SPYG: "SPDR Portfolio S&P 500 Growth ETF",
  SPYV: "SPDR Portfolio S&P 500 Value ETF",
  IUSG: "iShares Core S&P U.S. Growth ETF",
  IUSV: "iShares Core S&P U.S. Value ETF",
  MGK: "Vanguard Mega Cap Growth ETF",
  MGV: "Vanguard Mega Cap Value ETF",
  VO: "Vanguard Mid-Cap ETF",
  VB: "Vanguard Small-Cap ETF",
  IJR: "iShares Core S&P Small-Cap ETF",
  IJH: "iShares Core S&P Mid-Cap ETF",
  IJS: "iShares S&P Small-Cap 600 Value ETF",
  IWO: "iShares Russell 2000 Growth ETF",
  IWN: "iShares Russell 2000 Value ETF",
  IWP: "iShares Russell Mid-Cap Growth ETF",
  IWS: "iShares Russell Mid-Cap Value ETF",
  IWR: "iShares Russell Mid-Cap ETF",
  VOT: "Vanguard Mid-Cap Growth ETF",
  VOE: "Vanguard Mid-Cap Value ETF",
  VBK: "Vanguard Small-Cap Growth ETF",
  VBR: "Vanguard Small-Cap Value ETF",
  SCHA: "Schwab U.S. Small-Cap ETF",
  SCHM: "Schwab U.S. Mid-Cap ETF",
  SCHB: "Schwab U.S. Broad Market ETF",
  SPSM: "SPDR Portfolio S&P 600 Small Cap ETF",
  SPMD: "SPDR Portfolio S&P 400 Mid Cap ETF",
  VGT: "Vanguard Information Technology ETF",
  VHT: "Vanguard Health Care ETF",
  VFH: "Vanguard Financials ETF",
  VDE: "Vanguard Energy ETF",
  VIS: "Vanguard Industrials ETF",
  VDC: "Vanguard Consumer Staples ETF",
  VCR: "Vanguard Consumer Discretionary ETF",
  VPU: "Vanguard Utilities ETF",
  VAW: "Vanguard Materials ETF",
  VOX: "Vanguard Communication Services ETF",
  FTEC: "Fidelity MSCI Information Technology Index ETF",
  FHLC: "Fidelity MSCI Health Care Index ETF",
  FNCL: "Fidelity MSCI Financials Index ETF",
  FENY: "Fidelity MSCI Energy Index ETF",
  FIDU: "Fidelity MSCI Industrials Index ETF",
  FSTA: "Fidelity MSCI Consumer Staples Index ETF",
  FUTY: "Fidelity MSCI Utilities Index ETF",
  FMAT: "Fidelity MSCI Materials Index ETF",
  FDIS: "Fidelity MSCI Consumer Discretionary Index ETF",
  IYW: "iShares U.S. Technology ETF",
  IYH: "iShares U.S. Healthcare ETF",
  IYF: "iShares U.S. Financials ETF",
  IYE: "iShares U.S. Energy ETF",
  IYJ: "iShares U.S. Industrials ETF",
  IYK: "iShares U.S. Consumer Staples ETF",
  IYC: "iShares U.S. Consumer Discretionary ETF",
  IDU: "iShares U.S. Utilities ETF",
  IYM: "iShares U.S. Basic Materials ETF",
  IYZ: "iShares U.S. Telecommunications ETF",
  IYR: "iShares U.S. Real Estate ETF",
  IYG: "iShares U.S. Financial Services ETF",
  XOP: "SPDR S&P Oil & Gas Exploration & Production ETF",
  XES: "SPDR S&P Oil & Gas Equipment & Services ETF",
  XME: "SPDR S&P Metals & Mining ETF",
  XSD: "SPDR S&P Semiconductor ETF",
  XAR: "SPDR S&P Aerospace & Defense ETF",
  XHE: "SPDR S&P Health Care Equipment ETF",
  XHS: "SPDR S&P Health Care Services ETF",
  KIE: "SPDR S&P Insurance ETF",
  KBE: "SPDR S&P Bank ETF",
  KCE: "SPDR S&P Capital Markets ETF",
  XPH: "SPDR S&P Pharmaceuticals ETF",
  XSW: "SPDR S&P Software & Services ETF",
  XTL: "SPDR S&P Telecom ETF",
  XTN: "SPDR S&P Transportation ETF",
  VIG: "Vanguard Dividend Appreciation ETF",
  VYM: "Vanguard High Dividend Yield ETF",
  DVY: "iShares Select Dividend ETF",
  SDY: "SPDR S&P Dividend ETF",
  HDV: "iShares Core High Dividend ETF",
  FVD: "First Trust Value Line Dividend Index Fund",
  DON: "WisdomTree U.S. MidCap Dividend Fund",
  DES: "WisdomTree U.S. SmallCap Dividend Fund",
  DTD: "WisdomTree U.S. Total Dividend Fund",
  DLN: "WisdomTree U.S. LargeCap Dividend Fund",
  USMV: "iShares MSCI USA Min Vol Factor ETF",
  SPLV: "Invesco S&P 500 Low Volatility ETF",
  QUAL: "iShares MSCI USA Quality Factor ETF",
  MTUM: "iShares MSCI USA Momentum Factor ETF",
  VLUE: "iShares MSCI USA Value Factor ETF",
  EFAV: "iShares MSCI EAFE Min Vol Factor ETF",
  EEMV: "iShares MSCI Emerging Markets Min Vol Factor ETF",
  BSV: "Vanguard Short-Term Bond ETF",
  BIV: "Vanguard Intermediate-Term Bond ETF",
  BLV: "Vanguard Long-Term Bond ETF",
  VCIT: "Vanguard Intermediate-Term Corporate Bond ETF",
  VCSH: "Vanguard Short-Term Corporate Bond ETF",
  VCLT: "Vanguard Long-Term Corporate Bond ETF",
  VGIT: "Vanguard Intermediate-Term Treasury ETF",
  VGSH: "Vanguard Short-Term Treasury ETF",
  VGLT: "Vanguard Long-Term Treasury ETF",
  EDV: "Vanguard Extended Duration Treasury ETF",
  TLH: "iShares 10-20 Year Treasury Bond ETF",
  GOVT: "iShares U.S. Treasury Bond ETF",
  MUB: "iShares National Muni Bond ETF",
  TFI: "SPDR Nuveen Bloomberg Municipal Bond ETF",
  MBB: "iShares MBS ETF",
  BIL: "SPDR Bloomberg 1-3 Month T-Bill ETF",
  IUSB: "iShares Core Total USD Bond Market ETF",
  IGIB: "iShares 5-10 Year Investment Grade Corporate Bond ETF",
  IGSB: "iShares 1-5 Year Investment Grade Corporate Bond ETF",
  FLOT: "iShares Floating Rate Bond ETF",
  VT: "Vanguard Total World Stock ETF",
  VXUS: "Vanguard Total International Stock ETF",
  IXUS: "iShares Core MSCI Total International Stock ETF",
  ACWI: "iShares MSCI ACWI ETF",
  IEFA: "iShares Core MSCI EAFE ETF",
  IEMG: "iShares Core MSCI Emerging Markets ETF",
  SCHF: "Schwab International Equity ETF",
  SCHE: "Schwab Emerging Markets Equity ETF",
  SPDW: "SPDR Portfolio Developed World ex-US ETF",
  SPEM: "SPDR Portfolio Emerging Markets ETF",
  VEU: "Vanguard FTSE All-World ex-US ETF",
  VSS: "Vanguard FTSE All-World ex-US Small-Cap ETF",
  EFV: "iShares MSCI EAFE Value ETF",
  EFG: "iShares MSCI EAFE Growth ETF",
  EPP: "iShares MSCI Pacific ex Japan ETF",
  ILF: "iShares Latin America 40 ETF",
  ECH: "iShares MSCI Chile ETF",
  EPI: "WisdomTree India Earnings Fund",
  EWL: "iShares MSCI Switzerland ETF",
  EWP: "iShares MSCI Spain ETF",
  EWI: "iShares MSCI Italy ETF",
  EWS: "iShares MSCI Singapore ETF",
  EWM: "iShares MSCI Malaysia ETF",
  EWN: "iShares MSCI Netherlands ETF",
  EZA: "iShares MSCI South Africa ETF",
  IAU: "iShares Gold Trust",
  SGOL: "abrdn Physical Gold Shares ETF",
  SCHH: "Schwab U.S. REIT ETF",
  RWR: "SPDR Dow Jones REIT ETF",
  USRT: "iShares Core U.S. REIT ETF",
};

const STOCK_NAMES = {
  AAPL: "Apple Inc.",
  ABT: "Abbott Laboratories",
  ADBE: "Adobe Inc.",
  AMAT: "Applied Materials, Inc.",
  AMD: "Advanced Micro Devices, Inc.",
  AMGN: "Amgen Inc.",
  AMZN: "Amazon.com, Inc.",
  AVGO: "Broadcom Inc.",
  AXP: "American Express Company",
  BA: "Boeing Company",
  BAC: "Bank of America Corporation",
  BRK: "Berkshire Hathaway Inc.",
  "BRK-B": "Berkshire Hathaway Inc. Class B",
  CAT: "Caterpillar Inc.",
  COP: "ConocoPhillips",
  COST: "Costco Wholesale Corporation",
  CRM: "Salesforce, Inc.",
  CSCO: "Cisco Systems, Inc.",
  CVX: "Chevron Corporation",
  DE: "Deere & Company",
  DHR: "Danaher Corporation",
  DIS: "The Walt Disney Company",
  FDX: "FedEx Corporation",
  GLDM: "SPDR Gold MiniShares Trust",
  GLD: "SPDR Gold Shares",
  GOOG: "Alphabet Inc. Class C",
  GOOGL: "Alphabet Inc. Class A",
  GS: "Goldman Sachs Group, Inc.",
  HD: "The Home Depot, Inc.",
  HON: "Honeywell International Inc.",
  IBM: "International Business Machines Corporation",
  INTC: "Intel Corporation",
  ISRG: "Intuitive Surgical, Inc.",
  IWM: "iShares Russell 2000 ETF",
  JNJ: "Johnson & Johnson",
  JPM: "JPMorgan Chase & Co.",
  KLAC: "KLA Corporation",
  KO: "The Coca-Cola Company",
  LLY: "Eli Lilly and Company",
  LMT: "Lockheed Martin Corporation",
  LOW: "Lowe's Companies, Inc.",
  LRCX: "Lam Research Corporation",
  MA: "Mastercard Incorporated",
  MCD: "McDonald's Corporation",
  MDT: "Medtronic plc",
  META: "Meta Platforms, Inc.",
  MRK: "Merck & Co., Inc.",
  MS: "Morgan Stanley",
  MSFT: "Microsoft Corporation",
  NFLX: "Netflix, Inc.",
  NKE: "NIKE, Inc.",
  NVDA: "NVIDIA Corporation",
  ORCL: "Oracle Corporation",
  PEP: "PepsiCo, Inc.",
  PFE: "Pfizer Inc.",
  PG: "Procter & Gamble Company",
  QCOM: "QUALCOMM Incorporated",
  SBUX: "Starbucks Corporation",
  SLB: "Schlumberger Limited",
  SPY: "SPDR S&P 500 ETF Trust",
  SCHD: "Schwab U.S. Dividend Equity ETF",
  TLT: "iShares 20+ Year Treasury Bond ETF",
  TMO: "Thermo Fisher Scientific Inc.",
  TSLA: "Tesla, Inc.",
  TXN: "Texas Instruments Incorporated",
  UNH: "UnitedHealth Group Incorporated",
  UNP: "Union Pacific Corporation",
  UPS: "United Parcel Service, Inc.",
  V: "Visa Inc.",
  VOO: "Vanguard S&P 500 ETF",
  WFC: "Wells Fargo & Company",
  WMT: "Walmart Inc.",
  XOM: "Exxon Mobil Corporation",
};

const ADR_NAMES = {
  ASML: "ASML Holding N.V.",
  AZN: "AstraZeneca PLC",
  BHP: "BHP Group Limited",
  BP: "BP p.l.c.",
  HSBC: "HSBC Holdings plc",
  INFY: "Infosys Limited",
  MELI: "MercadoLibre, Inc.",
  NVO: "Novo Nordisk A/S",
  PBR: "Petroleo Brasileiro S.A. - Petrobras",
  RIO: "Rio Tinto Group",
  RY: "Royal Bank of Canada",
  SAP: "SAP SE",
  SHEL: "Shell plc",
  SONY: "Sony Group Corporation",
  TD: "The Toronto-Dominion Bank",
  TM: "Toyota Motor Corporation",
  TSM: "Taiwan Semiconductor Manufacturing Company Limited",
  TTE: "TotalEnergies SE",
  UL: "Unilever PLC",
  VALE: "Vale S.A.",
};

const CRYPTO_NAMES = {
  ADA: "Cardano",
  AVAX: "Avalanche",
  BCH: "Bitcoin Cash",
  DOGE: "Dogecoin",
  DOT: "Polkadot",
  LINK: "Chainlink",
  LTC: "Litecoin",
  XRP: "XRP",
};

function yahooAsset(symbol, market, name = symbol) {
  return {
    symbol,
    displaySymbol: symbol,
    dataSymbol: symbol,
    name,
    market,
    broker: "etoro",
    dataSource: "yahoo",
    quoteCurrency: "USD",
    minHistoryYears: 15,
  };
}

function cryptoAsset(base, name = base) {
  const symbol = `${base}USDT`;
  return {
    symbol,
    displaySymbol: symbol,
    dataSymbol: symbol,
    name,
    market: "crypto",
    broker: "binance",
    dataSource: "binance",
    quoteCurrency: "USDT",
    minHistoryYears: 7,
  };
}

const baseUniverse = [
  yahooAsset("SPY", "etf", "SPDR S&P 500 ETF Trust"),
  yahooAsset("QQQ", "etf", "Invesco QQQ Trust"),
  yahooAsset("IWM", "etf", "iShares Russell 2000 ETF"),
  yahooAsset("GLD", "etf", "SPDR Gold Shares"),
  yahooAsset("TLT", "etf", "iShares 20+ Year Treasury Bond ETF"),
  yahooAsset("XLE", "etf", "Energy Select Sector SPDR Fund"),
  yahooAsset("XLV", "etf", "Health Care Select Sector SPDR Fund"),
  yahooAsset("VOO", "etf", "Vanguard S&P 500 ETF"),
  yahooAsset("SCHD", "etf", "Schwab U.S. Dividend Equity ETF"),
  yahooAsset("GLDM", "etf", "SPDR Gold MiniShares Trust"),
  yahooAsset("AAPL", "stock", "Apple Inc."),
  yahooAsset("MSFT", "stock", "Microsoft Corporation"),
  yahooAsset("NVDA", "stock", "NVIDIA Corporation"),
  yahooAsset("AMZN", "stock", "Amazon.com, Inc."),
  yahooAsset("JPM", "stock", "JPMorgan Chase & Co."),
  yahooAsset("XOM", "stock", "Exxon Mobil Corporation"),
  yahooAsset("KO", "stock", "The Coca-Cola Company"),
  yahooAsset("WMT", "stock", "Walmart Inc."),
  yahooAsset("BRK-B", "stock", "Berkshire Hathaway Inc. Class B"),
  yahooAsset("META", "stock", "Meta Platforms, Inc."),
  cryptoAsset("BTC", "Bitcoin"),
  cryptoAsset("ETH", "Ethereum"),
  cryptoAsset("BNB", "BNB"),
  cryptoAsset("SOL", "Solana"),
];

const etfs = [
  "DIA", "MDY", "VTI", "VEA", "VWO", "EFA", "EEM", "EWJ", "EWU", "EWG",
  "EWC", "EWA", "EWY", "EWZ", "EWT", "EWW", "FXI", "XLF", "XLK", "XLY",
  "XLP", "XLU", "XLI", "XLB", "SMH", "IBB", "XBI", "XRT", "KRE", "ITB",
  "XHB", "GDX", "GDXJ", "VNQ", "SLV", "USO", "DBC", "IEF", "SHY", "TIP",
  "AGG", "BND", "LQD", "HYG", "EMB",
];

const additionalEtfs = [
  "IVV", "SPLG", "SCHX", "ITOT", "IWB", "IWV", "VV", "MGC", "OEF", "IWF",
  "IWD", "VUG", "VTV", "SCHG", "SCHV", "SPYG", "SPYV", "IUSG", "IUSV", "MGK",
  "MGV", "VO", "VB", "IJR", "IJH", "IJS", "IWO", "IWN", "IWP", "IWS",
  "IWR", "VOT", "VOE", "VBK", "VBR", "SCHA", "SCHM", "SCHB", "SPSM", "SPMD",
  "VGT", "VHT", "VFH", "VDE", "VIS", "VDC", "VCR", "VPU", "VAW", "VOX",
  "FTEC", "FHLC", "FNCL", "FENY", "FIDU", "FSTA", "FUTY", "FMAT", "FDIS", "IYW",
  "IYH", "IYF", "IYE", "IYJ", "IYK", "IYC", "IDU", "IYM", "IYZ", "IYR",
  "IYG", "XOP", "XES", "XME", "XSD", "XAR", "XHE", "XHS", "KIE", "KBE",
  "KCE", "XPH", "XSW", "XTL", "XTN", "VIG", "VYM", "DVY", "SDY", "HDV",
  "FVD", "DON", "DES", "DTD", "DLN", "USMV", "SPLV", "QUAL", "MTUM", "VLUE",
  "EFAV", "EEMV", "BSV", "BIV", "BLV", "VCIT", "VCSH", "VCLT", "VGIT", "VGSH",
  "VGLT", "EDV", "TLH", "GOVT", "MUB", "TFI", "MBB", "BIL", "IUSB", "IGIB",
  "IGSB", "FLOT", "VT", "VXUS", "IXUS", "ACWI", "IEFA", "IEMG", "SCHF", "SCHE",
  "SPDW", "SPEM", "VEU", "VSS", "EFV", "EFG", "EPP", "ILF", "ECH", "EPI",
  "EWL", "EWP", "EWI", "EWS", "EWM", "EWN", "EZA", "IAU", "SGOL", "SCHH",
  "RWR", "USRT",
];

const stocks = [
  "GOOGL", "GOOG", "TSLA", "BAC", "WFC", "GS", "MS", "V", "MA", "AXP",
  "UNH", "JNJ", "PFE", "MRK", "ABT", "TMO", "DHR", "MDT", "ISRG", "AMGN",
  "LLY", "PG", "PEP", "COST", "HD", "LOW", "MCD", "SBUX", "NKE", "DIS",
  "NFLX", "ORCL", "CSCO", "IBM", "INTC", "AMD", "QCOM", "TXN", "AVGO", "CRM",
  "ADBE", "AMAT", "LRCX", "KLAC", "CAT", "DE", "HON", "UNP", "UPS", "FDX",
  "BA", "LMT", "CVX", "COP", "SLB",
];

const adrs = [
  "TSM", "ASML", "SAP", "TM", "SONY", "NVO", "AZN", "UL", "BHP", "RIO",
  "VALE", "PBR", "BP", "SHEL", "TTE", "HSBC", "RY", "TD", "INFY", "MELI",
];

const cryptos = ["ADA", "XRP", "DOGE", "LTC", "BCH", "LINK", "DOT", "AVAX"];

export const TREND_RUNNER_UNIVERSE = [
  ...baseUniverse,
  ...etfs.map((symbol) => yahooAsset(symbol, "etf", ETF_NAMES[symbol] ?? symbol)),
  ...additionalEtfs.map((symbol) => yahooAsset(symbol, "etf", ETF_NAMES[symbol] ?? symbol)),
  ...stocks.map((symbol) => yahooAsset(symbol, "stock", STOCK_NAMES[symbol] ?? symbol)),
  ...adrs.map((symbol) => yahooAsset(symbol, "adr", ADR_NAMES[symbol] ?? symbol)),
  ...cryptos.map((symbol) => cryptoAsset(symbol, CRYPTO_NAMES[symbol] ?? symbol)),
];
